/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "email": {
        "OTP_SUBJECT": string;
        "OTP_BODY": string;
        "NEW_ACCOUNT_SUBJECT": string;
        "NEW_ACCOUNT_BODY": string;
        "SIGNUP_ACCOUNT_SUBJECT": string;
        "SIGNUP_ACCOUNT_BODY": string;
        "RESET_PASSWORD_SUBJECT": string;
        "RESET_PASSWORD_BODY": string;
    };
    "message": {
        "EMAIL_EXISTS": string;
        "GOOGLE_NOT_FOUND": string;
        "INVALID_CREDENTIAL": string;
        "INVALID_TOKEN": string;
        "IS_EXISTED": string;
        "NOT_PERMISSION": string;
        "NOT_FOUND": string;
        "PHONE_EXISTS": string;
        "REQUEST_LIMITED": string;
        "REQUEST_RESET_PASSWORD_SUCCESSFUL": string;
        "REQUEST_TOO_FAST": string;
        "TOKEN_EXPIRED": string;
        "USER_DELETED": string;
        "USER_DEACTIVATED": string;
        "USER_NOT_ACTIVATED_YET": string;
        "USER_NOT_EXISTS": string;
        "USER_PASSWORD_INCORRECT": string;
        "USER_EXISTED": string;
        "USER_REGISTRATION_SUCCESSFUL": string;
        "USER_RESEND_REGISTRATION_SUCCESSFUL": string;
    };
    "sms": {
        "OTP": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
